### PR TITLE
added a new method estimate_k_new

### PR DESCRIPTION
**Pull request by srividya22**
added a new method to estimate_k_new from R package fpc.

### CODE REVIEW

**Comment by rsutormin** [comment]
Hi Sri, are you sure you ran this method in tests? And it doesn't look like you used java_type_generator for stubs generation cause there is no change in server class. Let me make separate commit based on your changes. Is it ok for you?

**Comment by srividya22** [comment]
hi Roman,

It is ok. I ran the tests with the R script locally. Yes I didnt use the jave_type_geenrator for the stubs generation.

**Comment by rsutormin** [comment]
Sri, have a look at my commit with pieces of your code and unit tests. Does it look right for you? https://github.com/kbase/feature_values/commit/150c3a19d90b60615fe6cab541c58f4735e68016

**Comment by srividya22** [comment]
Hi Roman,

It is looks good to me.  I have also added the specs for the new method in
narrative_methods_specs_ci

https://github.com/kbase/narrative_method_specs_ci/pull/7

Thanks

Sri

**Pull request closed without merging**
